# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import quantiv_pb2 as quantiv__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in quantiv_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QuantivPricerStub:
    """The Pricing Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PriceBlackScholes = channel.unary_unary(
                '/quantiv.api.QuantivPricer/PriceBlackScholes',
                request_serializer=quantiv__pb2.PricingRequest.SerializeToString,
                response_deserializer=quantiv__pb2.PricingResponse.FromString,
                _registered_method=True)
        self.PriceBinomial = channel.unary_unary(
                '/quantiv.api.QuantivPricer/PriceBinomial',
                request_serializer=quantiv__pb2.BinomialRequest.SerializeToString,
                response_deserializer=quantiv__pb2.PricingResponse.FromString,
                _registered_method=True)
        self.PriceTrinomial = channel.unary_unary(
                '/quantiv.api.QuantivPricer/PriceTrinomial',
                request_serializer=quantiv__pb2.BinomialRequest.SerializeToString,
                response_deserializer=quantiv__pb2.PricingResponse.FromString,
                _registered_method=True)
        self.PriceMonteCarlo = channel.unary_unary(
                '/quantiv.api.QuantivPricer/PriceMonteCarlo',
                request_serializer=quantiv__pb2.BinomialRequest.SerializeToString,
                response_deserializer=quantiv__pb2.PricingResponse.FromString,
                _registered_method=True)
        self.PriceMerton = channel.unary_unary(
                '/quantiv.api.QuantivPricer/PriceMerton',
                request_serializer=quantiv__pb2.MertonRequest.SerializeToString,
                response_deserializer=quantiv__pb2.PricingResponse.FromString,
                _registered_method=True)
        self.PriceHeston = channel.unary_unary(
                '/quantiv.api.QuantivPricer/PriceHeston',
                request_serializer=quantiv__pb2.HestonRequest.SerializeToString,
                response_deserializer=quantiv__pb2.PricingResponse.FromString,
                _registered_method=True)


class QuantivPricerServicer:
    """The Pricing Service
    """

    def PriceBlackScholes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PriceBinomial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PriceTrinomial(self, request, context):
        """Uses same request as binomial (steps)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PriceMonteCarlo(self, request, context):
        """Uses same request (paths mapped to steps for simplicity or just use a specific one)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PriceMerton(self, request, context):
        """Advanced Models
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PriceHeston(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuantivPricerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PriceBlackScholes': grpc.unary_unary_rpc_method_handler(
                    servicer.PriceBlackScholes,
                    request_deserializer=quantiv__pb2.PricingRequest.FromString,
                    response_serializer=quantiv__pb2.PricingResponse.SerializeToString,
            ),
            'PriceBinomial': grpc.unary_unary_rpc_method_handler(
                    servicer.PriceBinomial,
                    request_deserializer=quantiv__pb2.BinomialRequest.FromString,
                    response_serializer=quantiv__pb2.PricingResponse.SerializeToString,
            ),
            'PriceTrinomial': grpc.unary_unary_rpc_method_handler(
                    servicer.PriceTrinomial,
                    request_deserializer=quantiv__pb2.BinomialRequest.FromString,
                    response_serializer=quantiv__pb2.PricingResponse.SerializeToString,
            ),
            'PriceMonteCarlo': grpc.unary_unary_rpc_method_handler(
                    servicer.PriceMonteCarlo,
                    request_deserializer=quantiv__pb2.BinomialRequest.FromString,
                    response_serializer=quantiv__pb2.PricingResponse.SerializeToString,
            ),
            'PriceMerton': grpc.unary_unary_rpc_method_handler(
                    servicer.PriceMerton,
                    request_deserializer=quantiv__pb2.MertonRequest.FromString,
                    response_serializer=quantiv__pb2.PricingResponse.SerializeToString,
            ),
            'PriceHeston': grpc.unary_unary_rpc_method_handler(
                    servicer.PriceHeston,
                    request_deserializer=quantiv__pb2.HestonRequest.FromString,
                    response_serializer=quantiv__pb2.PricingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quantiv.api.QuantivPricer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('quantiv.api.QuantivPricer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QuantivPricer:
    """The Pricing Service
    """

    @staticmethod
    def PriceBlackScholes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantiv.api.QuantivPricer/PriceBlackScholes',
            quantiv__pb2.PricingRequest.SerializeToString,
            quantiv__pb2.PricingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PriceBinomial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantiv.api.QuantivPricer/PriceBinomial',
            quantiv__pb2.BinomialRequest.SerializeToString,
            quantiv__pb2.PricingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PriceTrinomial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantiv.api.QuantivPricer/PriceTrinomial',
            quantiv__pb2.BinomialRequest.SerializeToString,
            quantiv__pb2.PricingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PriceMonteCarlo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantiv.api.QuantivPricer/PriceMonteCarlo',
            quantiv__pb2.BinomialRequest.SerializeToString,
            quantiv__pb2.PricingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PriceMerton(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantiv.api.QuantivPricer/PriceMerton',
            quantiv__pb2.MertonRequest.SerializeToString,
            quantiv__pb2.PricingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PriceHeston(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantiv.api.QuantivPricer/PriceHeston',
            quantiv__pb2.HestonRequest.SerializeToString,
            quantiv__pb2.PricingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
